services:
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - "${MYSQL_DATA_PATH}:/var/lib/mysql"

  flyway:
    image: flyway/flyway:11.17.1
    environment:
      FLYWAY_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}

    command: -configFiles=/flyway/conf/flyway.conf migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on:
      - db
