services:
  db:
    image: mysql:8.0.44-debian
    container_name: mysql-db-cafe
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: >
      --default-authentication-plugin=mysql_native_password
      --local-infile=1
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_CONTAINER_PORT}"
    networks:
      - cafenet

  flyway:
    build: .
    image: kenu21/flyway:latest
    container_name: flyway-cafe
    environment:
      FLYWAY_URL: jdbc:mysql://db:${MYSQL_CONTAINER_PORT}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&allowLoadLocalInfile=true&allowLocalInfile=true
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - cafenet
    command: ["migrate"]

networks:
  cafenet:
    name: cafenet
