apiVersion: v1
kind: Service
metadata:
  name: cafee-mysql
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: cafee-mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.containerPort }}
      targetPort: {{ .Values.mysql.containerPort }}
  type: ClusterIP
