apiVersion: v1
kind: Service
metadata:
  name: cafee-mysql
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: {{ .Values.mysql.label }}
  ports:
    - protocol: {{ .Values.mysql.protocol }}
      port: {{ .Values.mysql.containers.containerPort }}
      targetPort: {{ .Values.mysql.containers.containerPort }}
  type: ClusterIP
