namespaceName: mysql-ns

mysql:
  replicas: 1
  label: mysql-cafe-label
  name: mysql-cafe
  containers:
    name: cafe-mysql-container
    image: mysql:8.0.44-debian
    database: coffee_shop
    rootPassword:
    user:
    password:
    containerPort: 3306
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
  protocol: TCP

flyway:
  containers:
    name: cafe-flyway-container
    backoffLimit: 10
    restartPolicy: OnFailure
    image:
      repository: kenu21/cafe-flyway-image
      tag:
