namespaceName: mysql-ns

mysql:
  replicas: 1
  label: cafee-mysql-label
  name: cafee-mysql
  containers:
    name: mysql
    image: mysql:8.0.44-debian
    database: coffee_shop
    rootPassword:
    user:
    password:
    containerPort: 3306
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
  protocol: TCP

flyway:
  containers:
    name: flyway
    backoffLimit: 10
    restartPolicy: OnFailure
    image:
      repository: kenu21/flyway
      tag:
